/**
 * This file is part of VisiCut.
 * Copyright (C) 2011 - 2013 Thomas Oster <thomas.oster@rwth-aachen.de>
 * RWTH Aachen University - 52062 Aachen, Germany
 *
 *     VisiCut is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     VisiCut is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public License
 *     along with VisiCut.  If not, see <http://www.gnu.org/licenses/>.
 **/
package com.t_oster.uicomponents.warnings;

import com.t_oster.visicut.gui.MainView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Thomas Oster <thomas.oster@rwth-aachen.de>
 */
public class WarningPanel extends javax.swing.JPanel
{
  // Constants

  // Variables
  private List<Message> messages = new LinkedList<Message>();
  private Map<String, Message> messagesById = new HashMap<String, Message>();
  
  public void removeAllWarnings()
  {
    for (Message m: messages)
    {
      removeMessage(m);
    }
  }
  
  /**
   * Add a warning/info message and remove an old one of the same messageId if it exists
   * @param newMessage object for new message
   * @param messageId unique message identifier like 'camera error'. If null, no old message will be removed.
   */
  public void addMessageOnce(final Message newMessage, String messageId) {
    addMessage(newMessage);
    if (messageId != null) {
      removeMessageWithId(messageId, false);
      messagesById.put(messageId, newMessage);
    }
  }
  
  public void addMessage(final Message m)
  {
    messages.add(m);
    m.setCloseListener(new ActionListener(){
      public void actionPerformed(ActionEvent ae)
      {
        removeMessage(m);
      }
    });
    this.warningContainer.add(m);
    revalidate();
    repaint();
    setVisible(true);
  }
  
  public void removeMessage(final Message m) {
    removeMessage(m, true);
  }
  
  public void removeMessage(final Message m, boolean hidePanelIfEmpty) {
    messagesById.values().remove(m);
    messages.remove(m);
    warningContainer.remove(m);
    m.setCloseListener(null);
    
    revalidate();
    repaint();

    if (messages.isEmpty() && hidePanelIfEmpty)
    {
      setVisible(false);
    }
  }
  
  public void removeMessageWithId(String messageId, boolean hidePanelIfEmpty) {
    if (messagesById.containsKey(messageId)) {
      removeMessage(messagesById.get(messageId), hidePanelIfEmpty);
    }
  }
  
  public void removeMessageWithId(String messageId) {
    removeMessageWithId(messageId, true);
  }
  
  /**
   * Creates new form WarningPanel
   */
  public WarningPanel()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningContainer = new javax.swing.JPanel();

        warningContainer.setLayout(new javax.swing.BoxLayout(warningContainer, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel warningContainer;
    // End of variables declaration//GEN-END:variables
}
