/**
 * This file is part of VisiCut.
 * Copyright (C) 2011 - 2013 Thomas Oster <thomas.oster@rwth-aachen.de>
 * RWTH Aachen University - 52062 Aachen, Germany
 *
 *     VisiCut is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Lesser General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     VisiCut is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Lesser General Public License for more details.
 *
 *     You should have received a copy of the GNU Lesser General Public License
 *     along with VisiCut.  If not, see <http://www.gnu.org/licenses/>.
 **/
package com.t_oster.uicomponents.warnings;

import com.t_oster.visicut.gui.MainView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JButton;

/**
 *
 * @author Thomas Oster <thomas.oster@rwth-aachen.de>
 */
public class WarningPanel extends javax.swing.JPanel
{
  // Constants
  public static final int MESSAGE_ID_DEFAULT = 0;
  public static final int MESSAGE_ID_QR_CODE_EDIT_MESSAGE = 1;

  // Variables
  private List<Message> messages = new LinkedList<Message>();
  Message message_qr_code = null;
  
  public void removeAllWarnings()
  {
    for (Message m: messages)
    {
      warningContainer.remove(m);
      m.setCloseListener(null);  
    }
    messages.clear();
    // repaint + revalidate is always needed after removing components, see http://stackoverflow.com/questions/1097366/java-swing-revalidate-vs-repaint
    revalidate();
    repaint();
    setVisible(false);
  }
  
  public void addMessage(final Message m)
  {
    messages.add(m);
    m.setCloseListener(new ActionListener(){
      public void actionPerformed(ActionEvent ae)
      {
        messages.remove(m);
        warningContainer.remove(m);
        m.setCloseListener(null);
        revalidate();
        if (messages.isEmpty())
        {
          setVisible(false);
        }
      }
    });
    this.warningContainer.add(m);
    revalidate();
    setVisible(true);
  }
  
  public void addMessageWithId(final Message m, final int messageId, boolean closeButtonVisible)
  {
    if (m == null)
    {
      return;
    }

    boolean defaultCloseListener = true;
    
    switch (messageId)
    {
      // Message is automatically removed and closed
      case MESSAGE_ID_QR_CODE_EDIT_MESSAGE:
      {
        message_qr_code = m;
        defaultCloseListener = false;
        m.setCloseButtonVisible(closeButtonVisible);

        // Empty close listener
        m.setCloseListener(new ActionListener(){
          public void actionPerformed(ActionEvent ae)
          {
          }
        });

        break;
      }
      default:
      {
        return;
      }
    }
    
    messages.add(m);
    
    if (defaultCloseListener)
    {
      m.setCloseListener(new ActionListener(){
        public void actionPerformed(ActionEvent ae)
        {
          removeMessageWithId(messageId);
        }
      });
    }
    
    this.warningContainer.add(m);
    revalidate();
    setVisible(true);
  }
  
  public void removeMessageWithId(final int messageId)
  {
    Message m = null;
    
    switch (messageId)
    {
      case MESSAGE_ID_QR_CODE_EDIT_MESSAGE:
      {
        m = message_qr_code;
        message_qr_code = null;
        break;
      }
      default:
      {
        return;
      }
    }

    if (m == null)
    {
      return;
    }
    
    messages.remove(m);
    warningContainer.remove(m);
    m.setCloseListener(null);
    revalidate();
    repaint();

    if (messages.isEmpty())
    {
      setVisible(false);
    }
  }
  
  /**
   * Creates new form WarningPanel
   */
  public WarningPanel()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningContainer = new javax.swing.JPanel();

        warningContainer.setLayout(new javax.swing.BoxLayout(warningContainer, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(warningContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel warningContainer;
    // End of variables declaration//GEN-END:variables
}
