#!/bin/bash
#
# This file is part of VisiCut.
# Copyright (C) 2011 Thomas Oster <thomas.oster@rwth-aachen.de>
# RWTH Aachen University - 52062 Aachen, Germany
# 
#     VisiCut is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#    VisiCut is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Lesser General Public License for more details.
# 
#     You should have received a copy of the GNU Lesser General Public License
#     along with VisiCut.  If not, see <http://www.gnu.org/licenses/>.
#

# This script processes one HTTP request by capturing a photo
# and sending back an JPEG image

# Filename generated by gphoto2
FILE=capt0000.jpg
# Rotation of the image before sending
ROTATION=180

# delete the file if it exists
	rm -f $FILE
# take the snapshot
	gphoto2 --capture-image-and-download >/dev/null 2>&1
# rotate the image
	if [ "$ROTATION" != "0" ]
	then
		mogrify -rotate "$ROTATION>" $FILE
	fi
# output an HTTP header
	echo -ne "HTTP/1.0 200 OK\r\n"
	echo -ne "Content-Type: image/jpeg\r\n"
	echo -ne "Content-Length: $(stat -c %s $FILE)\r\n"
	echo -ne "Connection: close\r\n"
	echo -ne "\r\n"	
#output the file
	cat $FILE
#process all sent input
	while read line
	do
		echo $line > /dev/null
	done
