/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutoArrangePanel.java
 *
 * Created on Feb 1, 2015, 9:08:43 PM
 */
package com.t_oster.visicut.gui;

import com.mcp14.Autoarrange.AutoArrange;
import com.t_oster.visicut.gui.beans.PreviewPanel;
import java.awt.geom.NoninvertibleTransformException;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.jdesktop.application.Action;

/**
 *
 * @author sughoshkumar
 */
public class AutoArrangePanel extends javax.swing.JPanel
{
  private int count;
  private int totalNumberOfArrangements;
  public JFrame parentFrame;
  private int sliderValue;
  

  /** Creates new form AutoArrangePanel */
  public AutoArrangePanel(JFrame parent)
  {
    parentFrame = parent;
    count = 1;
    initComponents();
    totalNumberOfArrangements = AutoArrange.allValues.size();
    setStepCount();
    previousButton.setEnabled(false);
    if(totalNumberOfArrangements <= 1){
      nextButton.setEnabled(false);
      numberOfArrangements.setText("" + totalNumberOfArrangements + " Arrangement found");
    }
    else {
      numberOfArrangements.setText("" + totalNumberOfArrangements + " Arrangements found");
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distanceSlider = new javax.swing.JSlider();
        stepContainer = new javax.swing.JPanel();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        stepCount = new javax.swing.JLabel();
        numberOfArrangements = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        distanceSlider.setMajorTickSpacing(1);
        distanceSlider.setMaximum(10);
        distanceSlider.setPaintLabels(true);
        distanceSlider.setPaintTicks(true);
        distanceSlider.setSnapToTicks(true);
        distanceSlider.setValue(0);
        distanceSlider.setName("distanceSlider"); // NOI18N
        distanceSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                distanceSliderMouseReleased(evt);
            }
        });
        distanceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                distanceSliderStateChanged(evt);
            }
        });

        stepContainer.setName("stepContainer"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.t_oster.visicut.gui.VisicutApp.class).getContext().getActionMap(AutoArrangePanel.class, this);
        previousButton.setAction(actionMap.get("previousArrangement")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.t_oster.visicut.gui.VisicutApp.class).getContext().getResourceMap(AutoArrangePanel.class);
        previousButton.setText(resourceMap.getString("previousButton.text")); // NOI18N
        previousButton.setFocusable(false);
        previousButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousButton.setName("previousButton"); // NOI18N
        previousButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        nextButton.setAction(actionMap.get("nextArrangement")); // NOI18N
        nextButton.setText(resourceMap.getString("nextButton.text")); // NOI18N
        nextButton.setFocusable(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextButton.setName("nextButton"); // NOI18N
        nextButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        stepCount.setText(resourceMap.getString("stepCount.text")); // NOI18N
        stepCount.setName("stepCount"); // NOI18N

        numberOfArrangements.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfArrangements.setText(resourceMap.getString("numberOfArrangements.text")); // NOI18N
        numberOfArrangements.setName("numberOfArrangements"); // NOI18N

        org.jdesktop.layout.GroupLayout stepContainerLayout = new org.jdesktop.layout.GroupLayout(stepContainer);
        stepContainer.setLayout(stepContainerLayout);
        stepContainerLayout.setHorizontalGroup(
            stepContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stepContainerLayout.createSequentialGroup()
                .add(stepContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(stepContainerLayout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(previousButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stepCount)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nextButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(stepContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(numberOfArrangements)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        stepContainerLayout.setVerticalGroup(
            stepContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stepContainerLayout.createSequentialGroup()
                .add(8, 8, 8)
                .add(numberOfArrangements)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stepContainerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(previousButton)
                    .add(stepCount)
                    .add(nextButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        confirmButton.setAction(actionMap.get("confirm")); // NOI18N
        confirmButton.setText(resourceMap.getString("confirmButton.text")); // NOI18N
        confirmButton.setName("confirmButton"); // NOI18N

        discardButton.setAction(actionMap.get("discard")); // NOI18N
        discardButton.setText(resourceMap.getString("discardButton.text")); // NOI18N
        discardButton.setName("discardButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(stepContainer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addContainerGap(223, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(confirmButton)
                            .add(distanceSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 356, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(discardButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(distanceSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(stepContainer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(discardButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(confirmButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
    try
    {
      // TODO add your handling code here:
      nextButton.setEnabled(true);
      --count;
      if (count <= 1){
        previousButton.setEnabled(false);
      }
      boolean noPieces = MainView.previewStaticPanel.navigateThroughArrangements(count);
      if(!(noPieces)){
        System.out.println("No pieces to place!");
        stepCount.setText(count + "/" + totalNumberOfArrangements);
      }
      stepCount.setText(count + "/" + totalNumberOfArrangements);
    }
    catch (NoninvertibleTransformException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_previousButtonActionPerformed

  private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
    try
    {
      previousButton.setEnabled(true);
      ++count;
      if (count >= totalNumberOfArrangements){
        nextButton.setEnabled(false);
      }
      boolean noPieces = MainView.previewStaticPanel.navigateThroughArrangements(count);
      if(!(noPieces)){
        System.out.println("No pieces to place!");
        stepCount.setText(count + "/" + totalNumberOfArrangements);
      }
      stepCount.setText(count + "/" + totalNumberOfArrangements);
    }
    catch (NoninvertibleTransformException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_nextButtonActionPerformed

  private void distanceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_distanceSliderStateChanged
    // TODO add your handling code here:
    sliderValue = distanceSlider.getValue();
  }//GEN-LAST:event_distanceSliderStateChanged

  private void distanceSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distanceSliderMouseReleased
    // TODO add your handling code here:
    try
    {
      // TODO add your handling code here:
      MainView.previewStaticPanel.autoArrange(distanceSlider.getValue());
      totalNumberOfArrangements = AutoArrange.allValues.size();
      count = 1;
      setStepCount();
      previousButton.setEnabled(false);
      nextButton.setEnabled(true);
      if(totalNumberOfArrangements <= 1){
        nextButton.setEnabled(false);
        numberOfArrangements.setText("" + totalNumberOfArrangements + " Arrangement found");
      }
      else {
        numberOfArrangements.setText("" + totalNumberOfArrangements + " Arrangements found");
      }
      
      
      setStepCount();
    }
    catch (FileNotFoundException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (UnsupportedEncodingException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NoninvertibleTransformException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    
  }//GEN-LAST:event_distanceSliderMouseReleased

  
  // to set the step count value
  private void setStepCount(){
    stepCount.setText(count + "/" + totalNumberOfArrangements);
  }

  @Action
  public void discard()
  {
    try
    {
      MainView.previewStaticPanel.autoArrange(0);
      parentFrame.dispose();
      MainView.arrangeFrame = null;
    }
    catch (FileNotFoundException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (UnsupportedEncodingException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (NoninvertibleTransformException ex)
    {
      Logger.getLogger(AutoArrangePanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  @Action
  public void confirm()
  {
    parentFrame.dispose();
    MainView.arrangeFrame = null;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton discardButton;
    private javax.swing.JSlider distanceSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel numberOfArrangements;
    private javax.swing.JButton previousButton;
    private javax.swing.JPanel stepContainer;
    private javax.swing.JLabel stepCount;
    // End of variables declaration//GEN-END:variables
}
