package com.t_oster.visicut.gui.parameterpanel;

import com.t_oster.uicomponents.parameter.Parameter;
import com.t_oster.visicut.VisicutModel;
import com.t_oster.visicut.gui.MainView;
import com.t_oster.visicut.model.PlfPart;
import com.t_oster.visicut.model.graphicelements.ImportException;
import com.t_oster.visicut.model.graphicelements.psvgsupport.PSVGImporter;
import com.t_oster.uicomponents.parameter.ParameterTableModel;
import com.t_oster.visicut.model.graphicelements.psvgsupport.ParametricPlfPart;
import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Thomas Oster <thomas.oster@rwth-aachen.de>
 */
public class ParameterPanel extends javax.swing.JPanel
{

  private ParameterTableModel model = new ParameterTableModel();

  /**
   * Creates new form ParameterPanel
   */
  public ParameterPanel()
  {
    initComponents();
    this.parameterJTable1.setModel(model);
    VisicutModel.getInstance().addPropertyChangeListener(new PropertyChangeListener()
    {
      public void propertyChange(PropertyChangeEvent pce)
      {
        if (!ignoreChanges && VisicutModel.PROP_SELECTEDPART.equals(pce.getPropertyName()))
        {
          refresh();
        }
        else if (VisicutModel.PROP_PLF_PART_REMOVED.equals(pce.getPropertyName())|| VisicutModel.PROP_PLF_PART_UPDATED.equals(pce.getPropertyName()))
        {
          refresh();
        }
      }
    });
    this.model.addTableModelListener(new TableModelListener()
    {
      public void tableChanged(TableModelEvent tme)
      {
        if (!ignoreChanges)
        {
          applyParameters();
        }
      }
    });
  }
  private boolean ignoreChanges = false;

  private void applyParameters()
  {
    ignoreChanges = true;
    PlfPart p = VisicutModel.getInstance().getSelectedPart();
    if (p != null && p instanceof ParametricPlfPart)
    {
      try
      {
        ((ParametricPlfPart) p).applyParameters();
        VisicutModel.getInstance().firePartUpdated(p);
      }
      catch (Exception e)
      {
        MainView.getInstance().getDialog().showErrorMessage(e);
      }
    }
    ignoreChanges = false;
  }

  public void refresh()
  {
    ignoreChanges = true;
    PlfPart p = VisicutModel.getInstance().getSelectedPart();
    if (p != null && p instanceof ParametricPlfPart)
    {
      Map<String, Parameter> params = ((ParametricPlfPart) p).getParameters();
      model.setParameterMap(params);
    }
    else
    {
      model.setParameterMap(null);
    }
    ignoreChanges = false;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane2 = new javax.swing.JScrollPane();
    parameterJTable1 = new com.t_oster.uicomponents.parameter.ParameterJTable();

    parameterJTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane2.setViewportView(parameterJTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane2;
  private com.t_oster.uicomponents.parameter.ParameterJTable parameterJTable1;
  // End of variables declaration//GEN-END:variables
}
