#!/bin/sh
#
# derived from distribute/linux/install:post_install(){}

[ -x /usr/bin/xdg-icon-resource ] && xdg-icon-resource install --context mimetypes --size 32 /usr/share/pixmaps/visicut-32.png application-x-plf
[ -x /usr/bin/xdg-icon-resource ] && xdg-icon-resource install --context mimetypes --size 32 /usr/share/pixmaps/visicut-32.png application-x-ls
[ -x /usr/bin/xdg-icon-resource ] && xdg-icon-resource install --context mimetypes --size 48 /usr/share/pixmaps/visicut-48.png application-x-plf
[ -x /usr/bin/xdg-icon-resource ] && xdg-icon-resource install --context mimetypes --size 48 /usr/share/pixmaps/visicut-48.png application-x-ls

[ -x /usr/bin/xdg-mime ] && xdg-mime install /usr/share/visicut/plf-mime.xml || true
[ -x /usr/bin/xdg-mime ] && xdg-mime install /usr/share/visicut/ls-mime.xml || true

[ -x /usr/bin/update-desktop-database ] && update-desktop-database -q || true
[ -x /usr/bin/gtk-update-icon-cache ] && gtk-update-icon-cache -q -t -f usr/share/icons/hicolor || true

echo "Adding inkscape extension"
mkdir -p /usr/share/inkscape/extensions;  ln -sf /usr/share/visicut/inkscape_extension/* /usr/share/inkscape/extensions/
