/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThingiverseUploadDialog.java
 *
 * Created on 24.01.2015, 18:04:13
 */
package com.tur0kk.thingiverse.gui;

import com.github.sarxos.webcam.Webcam;
import com.t_oster.visicut.gui.MainView;
import javax.swing.JDialog;
import javax.swing.WindowConstants;

/**
 *
 * @author Sven
 */
public class ThingiverseUploadDialog extends javax.swing.JDialog
{
  private Thread livecamThread;
  final private MainView mainview;

  /** Creates new form ThingiverseUploadDialog */
  public ThingiverseUploadDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    
    // save parent for modality faking
    this.mainview = (MainView) parent;

    
    // no need to keep state
    this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    
    
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpCams = new javax.swing.ButtonGroup();
        rdbtnWebcam = new javax.swing.JRadioButton();
        rdbtnVisicut = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        grpCams.add(rdbtnWebcam);
        rdbtnWebcam.setSelected(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.t_oster.visicut.gui.VisicutApp.class).getContext().getResourceMap(ThingiverseUploadDialog.class);
        rdbtnWebcam.setText(resourceMap.getString("rdbtnWebcam.text")); // NOI18N
        rdbtnWebcam.setName("rdbtnWebcam"); // NOI18N

        rdbtnVisicut.setText(resourceMap.getString("rdbtnVisicut.text")); // NOI18N
        rdbtnVisicut.setName("rdbtnVisicut"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(556, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnVisicut)
                    .addComponent(rdbtnWebcam))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbtnWebcam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnVisicut)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grpCams;
    private javax.swing.JRadioButton rdbtnVisicut;
    private javax.swing.JRadioButton rdbtnWebcam;
    // End of variables declaration//GEN-END:variables

    /*
   * Camera functions
   */
  /*
   * returns wether a camera is plugged in
   */
  private boolean isCameraDetected(){
    if(rdbtnWebcam.isSelected()){ // webcam
      Webcam webcam = Webcam.getDefault();
      if (webcam != null) { 
        return true;
      } else {
        return false;
      }
    }
    else{
      // visicam
      return mainview.isVisiCamDetected();
    }

  }
  
}
